// Generated by build-tokens.mjs
// Drop into your Nuxt project as app.config.ts (or merge with existing).
// Nuxt UI v3 reads colors from this config; component sizing/spacing is driven
// by the CSS variables in tokens.css.

export default defineAppConfig({
  ui: {
    colors: {
      primary: 'blue',
      neutral: 'zinc',
    },
    // Example: bind Nuxt UI button slot to our CSS variables.
    // Uncomment / extend as needed.
    // button: {
    //   slots: {
    //     base: 'rounded-[var(--button-radius)] gap-[var(--button-gap)] font-[var(--button-font-weight)]',
    //   },
    // },
  },
});
