// GENERATED by scripts/gen-nuxt-vocab.ts from @nuxt/ui v4.7.1 — do not edit by hand.
// Re-run: npm run gen:vocab
export const GENERATED_NUXT_SLOTS: ReadonlyMap<string, ReadonlySet<string>> = new Map([
  ["button", new Set(["base","label","leadingIcon","leadingAvatar","leadingAvatarSize","trailingIcon"])],
  ["badge", new Set(["base","label","leadingIcon","leadingAvatar","leadingAvatarSize","trailingIcon"])],
  ["input", new Set(["root","base","leading","leadingIcon","leadingAvatar","leadingAvatarSize","trailing","trailingIcon"])],
  ["textarea", new Set(["leading","trailing"])],
  ["card", new Set(["root","header","title","description","body","footer"])],
  ["modal", new Set(["overlay","content","header","wrapper","body","footer","title","description","close"])],
  ["kbd", new Set([])],
  ["chip", new Set(["root","base"])],
  ["checkbox", new Set(["root","container","base","indicator","icon","wrapper","label","description"])],
  ["radio", new Set(["root","fieldset","legend","item","container","base","indicator","wrapper","label","description"])],
  ["switch", new Set(["root","base","container","thumb","icon","wrapper","label","description"])],
  ["nav", new Set(["root","list","label","item","link","linkLeadingIcon","linkLeadingAvatar","linkLeadingAvatarSize","linkLeadingChipSize","linkTrailing","linkTrailingBadge","linkTrailingBadgeSize","linkTrailingIcon","linkLabel","linkLabelExternalIcon","childList","childLabel","childItem","childLink","childLinkWrapper","childLinkIcon","childLinkLabel","childLinkLabelExternalIcon","childLinkDescription","separator","viewportWrapper","viewport","content","indicator","arrow"])],
  ["dropdown", new Set(["content","input","empty","viewport","arrow","group","label","separator","item","itemLeadingIcon","itemLeadingAvatar","itemLeadingAvatarSize","itemTrailing","itemTrailingIcon","itemTrailingKbds","itemTrailingKbdsSize","itemWrapper","itemLabel","itemDescription","itemLabelExternalIcon"])],
  ["table", new Set(["root","base","caption","thead","tbody","tfoot","tr","th","td","separator","empty","loading"])],
  ["progress", new Set(["root","base","indicator","status","steps","step"])],
  ["accordion", new Set(["root","item","header","trigger","content","body","leadingIcon","trailingIcon","label"])],
  ["toast", new Set(["root","wrapper","title","description","icon","avatar","avatarSize","actions","progress","close"])],
  ["alert", new Set(["root","wrapper","title","description","icon","avatar","avatarSize","actions","close"])],
  ["tooltip", new Set(["content","arrow","text","kbds","kbdsSize"])],
  ["popover", new Set(["content","arrow"])],
  ["tabs", new Set(["root","list","indicator","trigger","leadingIcon","leadingAvatar","leadingAvatarSize","label","trailingBadge","trailingBadgeSize","content"])],
  ["select", new Set(["root","base","value","placeholder","arrow","content","viewport","group","empty","label","separator","item","itemLeadingIcon","itemLeadingAvatar","itemLeadingAvatarSize","itemLeadingChip","itemLeadingChipSize","itemTrailing","itemTrailingIcon","itemWrapper","itemLabel","itemDescription"])],
  ["breadcrumb", new Set(["root","list","item","link","linkLeadingIcon","linkLeadingAvatar","linkLeadingAvatarSize","linkLabel","separator","separatorIcon"])],
  ["drawer", new Set(["overlay","content","handle","container","header","title","description","body","footer"])],
  ["avatar", new Set(["root","image","fallback","icon"])],
]);

export const GENERATED_COMPONENTS: readonly string[] = ["button","badge","input","textarea","card","modal","kbd","chip","checkbox","radio","switch","nav","dropdown","table","progress","accordion","toast","alert","tooltip","popover","tabs","select","breadcrumb","drawer","avatar"];
