// app.config.ts renderer — produces the Nuxt UI v4 app config.
// Nuxt UI v4 reads colors here; component sizing/spacing comes from
// tokens.css custom properties. We emit a minimal config plus
// commented-out slot bindings derived from the component layer so the
// user can see which Nuxt UI slots have matching token coverage.

import type { TextRenderer, TokenGraph } from "../token-graph.js";
import { LineBuilder } from "./line-builder.js";

const COMPONENT_PREFIXES = ["button", "input", "card", "badge", "modal"];

export const appConfigRenderer: TextRenderer = {
  id: "app.config.ts",
  render(graph: TokenGraph) {
    const lb = new LineBuilder();
    lb.push("// Generated by buildGraph + appConfigRenderer");
    lb.push("// Drop into your Nuxt project as app.config.ts (or merge).");
    lb.push("// Nuxt UI v4 reads colors here; sizing/spacing comes from tokens.css.");
    lb.blank();
    lb.push("export default defineAppConfig({");
    lb.push("  ui: {");
    lb.push("    colors: {");
    lb.push("      primary: 'blue',");
    lb.push("      neutral: 'zinc',");
    lb.push("    },");

    for (const prefix of COMPONENT_PREFIXES) {
      const matching = [...graph.nodes.values()].filter(
        (n) => n.layer === "component" && n.id.startsWith(`${prefix}-`),
      );
      if (matching.length === 0) continue;
      lb.push(`    // ${prefix}: tokens detected — uncomment + customize as needed`);
      lb.push(`    // ${prefix}: {`);
      lb.push(`    //   slots: {`);
      lb.push(
        `    //     base: '${matching
          .slice(0, 4)
          .map((n) => `[--${n.id}]`)
          .join(" ")}${matching.length > 4 ? " /* …" + (matching.length - 4) + " more */" : ""}',`,
      );
      for (const node of matching) {
        lb.pushWithToken(`    //   },`, node.id);
        break;
      }
      lb.push(`    // },`);
    }

    lb.push("  },");
    lb.push("});");
    lb.blank();
    return lb.build();
  },
};
