// Nuxt UI v4 app.config.ts renderer.
//
// Emits a defineAppConfig block with:
//   ui.colors  — standard Nuxt UI color-role mapping
//   ui.<component> — slot/variant recipe blocks for components in COMPONENT_ALLOW_LIST
//
// Recipe blocks are only emitted when component-layer tokens are present in the graph
// and match the slot-mapping heuristics. The body is always rendered as a suggestion —
// the consuming project may merge or replace.

import type { TextRenderer, TokenGraph, CompletenessScore } from "../token-graph.js";
import type { RenderedText } from "../token-graph.js";
import { LineBuilder } from "./line-builder.js";
import {
  buildComponentRecipes,
  type ComponentRecipe,
} from "../recipe-engine.js";
import type { SlotMappingOverride } from "../slot-mapping.js";

export interface AppConfigRendererOptions {
  slotMappingOverride?: SlotMappingOverride;
  defaultSizeByComponent?: Readonly<Record<string, string>>;
  /**
   * Completeness scores from scanGraph(). When present, each incomplete
   * variant gets a `// Incomplete in Figma: missing X, Y` comment.
   * When absent, no comments are emitted (graceful fallback).
   */
  completeness?: ReadonlyArray<CompletenessScore>;
}

interface AppConfigRenderer extends TextRenderer {
  render(graph: TokenGraph, options?: AppConfigRendererOptions): RenderedText;
}

interface RoleMapping {
  readonly primary: string;
  readonly neutral: string;
  readonly secondary: string;
  readonly success: string;
  readonly info: string;
  readonly warning: string;
  readonly error: string;
}

export const COMPONENT_ALLOW_LIST = [
  "button", "badge", "input", "textarea", "card", "modal", "kbd", "chip",
  "checkbox", "radio", "switch", "nav", "dropdown", "table", "progress",
] as const;

const DEFAULT_ROLES: RoleMapping = {
  primary: "blue",
  neutral: "neutral",
  secondary: "sky",
  success: "emerald",
  info: "sky",
  warning: "amber",
  error: "rose",
};

export const appConfigRenderer: AppConfigRenderer = {
  id: "app.config.ts",
  render(graph: TokenGraph, options?: AppConfigRendererOptions) {
    const roles = deriveRoles(graph);
    const recipes = buildComponentRecipes(graph, {
      components: COMPONENT_ALLOW_LIST,
      slotMappingOverride: options?.slotMappingOverride,
      defaultSizeByComponent: options?.defaultSizeByComponent,
    });
    const lb = new LineBuilder();
    lb.push("// Generated by build-cli — Nuxt UI v4 component recipes + color role mapping");
    lb.push("// Generated from Figma component-layer tokens. Re-run the build to regenerate.");
    lb.blank();
    lb.push("export default defineAppConfig({");
    lb.push("  ui: {");
    lb.push("    colors: {");
    for (const role of [
      "primary",
      "neutral",
      "secondary",
      "success",
      "info",
      "warning",
      "error",
    ] as const) {
      lb.push(`      ${role}: ${JSON.stringify(roles[role])},`);
    }
    lb.push("    },");
    for (const component of COMPONENT_ALLOW_LIST) {
      const recipe = recipes[component];
      if (recipe !== undefined) {
        const componentCompleteness = options?.completeness?.filter(
          (c) => c.component === component,
        );
        emitRecipe(lb, component, recipe, componentCompleteness);
      }
    }
    lb.push("  },");
    lb.push("});");
    lb.blank();
    return lb.build();
  },
};

/**
 * Returns the fixed DEFAULT_ROLES mapping. Hue-proximity matching against the
 * graph's semantic palette is not implemented; the `_graph` parameter is kept
 * so a future heuristic can read it without changing the call site. The
 * Inspector frames the output as a "suggestion", so a constant mapping is honest.
 */
function deriveRoles(_graph: TokenGraph): RoleMapping {
  return DEFAULT_ROLES;
}

function emitRecipe(
  lb: LineBuilder,
  name: string,
  recipe: ComponentRecipe,
  componentCompleteness?: ReadonlyArray<CompletenessScore>,
): void {
  lb.push(`    ${name}: {`);

  const slotEntries = Object.entries(recipe.slots);
  if (slotEntries.length > 0) {
    lb.push("      slots: {");
    for (const [slot, classes] of slotEntries) {
      lb.push(`        ${slot}: ${JSON.stringify(classes)},`);
    }
    lb.push("      },");
  }

  const variantsAny =
    Object.keys(recipe.variants.size ?? {}).length > 0 ||
    Object.keys(recipe.variants.color ?? {}).length > 0 ||
    Object.keys(recipe.variants.variant ?? {}).length > 0;

  if (variantsAny) {
    lb.push("      variants: {");
    for (const axis of ["size", "color", "variant"] as const) {
      const axisMap = recipe.variants[axis];
      if (!axisMap || Object.keys(axisMap).length === 0) continue;
      lb.push(`        ${axis}: {`);
      const sortedKeys = Object.keys(axisMap).sort();
      for (const variantKey of sortedKeys) {
        const slotMap = axisMap[variantKey];
        if (slotMap === undefined) continue;
        lb.push(`          ${variantKey}: {`);

        // Emit completeness comment when this variant has missing utilities.
        const score = componentCompleteness?.find(
          (c) => c.axis === axis && c.variantKey === variantKey,
        );
        if (score !== undefined && score.missingUtilities.length > 0) {
          lb.push(
            `            // Incomplete in Figma: missing ${score.missingUtilities.join(", ")}`,
          );
        }

        for (const [slot, classes] of Object.entries(slotMap)) {
          lb.push(`            ${slot}: ${JSON.stringify(classes)},`);
        }
        lb.push("          },");
      }
      lb.push("        },");
    }
    lb.push("      },");
  }

  lb.push("    },");
}
