// Minimal Nuxt UI v4 color-role mapping.
//
// Emits a defineAppConfig block with ui.colors mapping standard Nuxt UI
// roles (primary, neutral, secondary, success, info, warning, error) to
// palette names derived from the loaded graph. The body is always
// rendered as a suggestion — the consuming project may merge or replace.

import type { TextRenderer, TokenGraph } from "../token-graph.js";
import { LineBuilder } from "./line-builder.js";

interface RoleMapping {
  readonly primary: string;
  readonly neutral: string;
  readonly secondary: string;
  readonly success: string;
  readonly info: string;
  readonly warning: string;
  readonly error: string;
}

const DEFAULT_ROLES: RoleMapping = {
  primary: "blue",
  neutral: "neutral",
  secondary: "sky",
  success: "emerald",
  info: "sky",
  warning: "amber",
  error: "rose",
};

export const appConfigRenderer: TextRenderer = {
  id: "app.config.ts",
  render(graph: TokenGraph) {
    const roles = deriveRoles(graph);
    const lb = new LineBuilder();
    lb.push("// Generated by build-cli — Nuxt UI v4 color role mapping");
    lb.push("// Suggested defaults; adjust to your taste in the consuming Nuxt project.");
    lb.blank();
    lb.push("export default defineAppConfig({");
    lb.push("  ui: {");
    lb.push("    colors: {");
    for (const role of [
      "primary",
      "neutral",
      "secondary",
      "success",
      "info",
      "warning",
      "error",
    ] as const) {
      lb.push(`      ${role}: ${JSON.stringify(roles[role])},`);
    }
    lb.push("    },");
    lb.push("  },");
    lb.push("});");
    lb.blank();
    return lb.build();
  },
};

/**
 * Heuristic role derivation from the graph's semantic palette names.
 * For PR 1, returns DEFAULT_ROLES — Inspector's "suggestion" framing
 * is honest because we have not yet implemented hue-proximity matching.
 * PR 2 may sharpen this once the build is wired end-to-end.
 */
function deriveRoles(_graph: TokenGraph): RoleMapping {
  return DEFAULT_ROLES;
}
