// CSS renderer — produces tokens.css from a TokenGraph.
// Three cascade sections matching build-tokens.mjs:
//   1. @theme primitives (Tailwind-native namespaces)
//   2. :root semantic light + html.dark semantic dark overrides
//   3. :root component overrides (plain CSS variables)

import type {
  GraphLayer,
  TextRenderer,
  Theme,
  TokenGraph,
  TokenNode,
} from "../token-graph.js";
import { LineBuilder } from "./line-builder.js";

const HEADER = [
  "/* Generated by buildGraph + cssRenderer — do not edit by hand */",
  "/* Source: components/*.tokens.json (Figma W3C export) */",
];

function nodesByLayer(
  graph: TokenGraph,
  layer: GraphLayer,
): TokenNode[] {
  const out: TokenNode[] = [];
  for (const node of graph.nodes.values()) {
    if (node.layer === layer) out.push(node);
  }
  return out;
}

/**
 * Format a single declaration. If a resolved alias for the requested
 * variant exists, emit `var(--target)`, else emit the literal cssValue.
 * Returns `null` if there is no value for this variant on this node.
 */
function declFor(
  graph: TokenGraph,
  node: TokenNode,
  variant: "base" | Theme,
  useAlias: boolean,
): string | null {
  const aliasVariant = useAlias ? node.alias[variant] : undefined;
  const value =
    aliasVariant !== undefined
      ? `var(--${cssVarName(graph.nodes.get(aliasVariant.to) ?? { ...node, id: aliasVariant.to })})`
      : node.cssValue[variant];
  if (value === undefined || /^\{[^{}]+\}$/.test(value) || value === "undefined") {
    return null;
  }
  return `  --${cssVarName(node)}: ${value};`;
}

function ensurePrefix(id: string, prefix: string): string {
  return id.startsWith(`${prefix}-`) ? id : `${prefix}-${id}`;
}

function cssVarName(node: Pick<TokenNode, "id" | "type">): string {
  if (node.id.startsWith("color-") || node.id.startsWith("spacing-") || node.id.startsWith("radius-") || node.id.startsWith("shadow-") || node.id.startsWith("font-") || node.id.startsWith("font-weight-") || node.id.startsWith("text-") || node.id.startsWith("tracking-") || node.id.startsWith("leading-") || node.id.startsWith("border-width-")) {
    return node.id;
  }

  if (node.type !== "color" && node.type !== "shadow" && node.type !== "fontFamily" && node.type !== "fontWeight" && !node.id.startsWith("font-size-") && !node.id.startsWith("line-height-") && !node.id.startsWith("letter-spacing-") && !node.id.startsWith("rounded-") && !node.id.startsWith("border-") && !node.id.startsWith("spacing-")) {
    return node.id;
  }

  if (node.type === "color") return ensurePrefix(node.id, "color");
  if (node.type === "shadow") return ensurePrefix(node.id, "shadow");
  if (node.type === "fontFamily") return ensurePrefix(node.id, "font");
  if (node.type === "fontWeight") return ensurePrefix(node.id, "font-weight");

  if (node.id.startsWith("font-family-")) return ensurePrefix(node.id.slice("font-family-".length), "font");
  if (/-font-family(-|$)/.test(node.id)) return ensurePrefix(node.id, "font");

  if (node.id.startsWith("font-size-")) return ensurePrefix(node.id.slice("font-size-".length), "text");
  if (/-font-size(-|$)/.test(node.id)) return ensurePrefix(node.id, "text");

  if (node.id.startsWith("line-height-")) return ensurePrefix(node.id.slice("line-height-".length), "leading");
  if (/-line-height(-|$)/.test(node.id)) return ensurePrefix(node.id, "leading");

  if (node.id.startsWith("letter-spacing-")) return ensurePrefix(node.id.slice("letter-spacing-".length), "tracking");
  if (/-letter-spacing(-|$)/.test(node.id)) return ensurePrefix(node.id, "tracking");

  if (node.id.startsWith("rounded-")) return ensurePrefix(node.id.slice("rounded-".length), "radius");
  if (/^(radius|rounded)-/.test(node.id) || /-(radius|rounded)(-|$)/.test(node.id)) {
    return ensurePrefix(node.id, "radius");
  }

  if (node.id.startsWith("border-width-")) {
    return ensurePrefix(node.id.slice("border-width-".length), "border-width");
  }
  if (node.id.startsWith("border-")) {
    return ensurePrefix(node.id.slice("border-".length), "border-width");
  }

  if (node.id.startsWith("spacing-") || /-(spacing|padding|gap|size|width|height|offset)(-|$)/.test(node.id)) {
    return ensurePrefix(node.id, "spacing");
  }

  return node.id;
}

function emitBlock(
  lb: LineBuilder,
  selector: string,
  graph: TokenGraph,
  nodes: readonly TokenNode[],
  variant: "base" | Theme,
  useAlias: boolean,
  sectionLabel?: string,
): void {
  if (sectionLabel) lb.push(sectionLabel);
  lb.push(`${selector} {`);
  for (const node of nodes) {
    const decl = declFor(graph, node, variant, useAlias);
    if (decl !== null) lb.pushWithToken(decl, node.id);
  }
  lb.push("}");
  lb.blank();
}

export const cssRenderer: TextRenderer = {
  id: "tokens.css",
  render(graph: TokenGraph) {
    const lb = new LineBuilder();
    for (const h of HEADER) lb.push(h);
    lb.blank();

    const primitives = nodesByLayer(graph, "primitive");
    const semantics = nodesByLayer(graph, "semantic");
    const components = nodesByLayer(graph, "component");

    // Layer 1: primitives — literal values in @theme so Tailwind can
    // synthesize utility classes from the recognized namespaces.
    if (primitives.length > 0) {
      emitBlock(lb, "@theme", graph, primitives, "base", false);
    }

    // Layer 2a: semantic light/default — plain CSS variables for reliable
    // component consumption via var(--token).
    const lightNodes = semantics.filter((n) => n.cssValue.light !== undefined);
    if (lightNodes.length > 0) {
      emitBlock(
        lb,
        ":root",
        graph,
        lightNodes,
        "light",
        true,
        "/* Semantic — light theme (default) */",
      );
    }

    // Layer 2b: semantic dark — alias-resolved.
    const darkNodes = semantics.filter((n) => n.cssValue.dark !== undefined);
    if (darkNodes.length > 0) {
      emitBlock(
        lb,
        'html.dark, [data-theme="dark"]',
        graph,
        darkNodes,
        "dark",
        true,
        "/* Semantic — dark theme */",
      );
    }

    // Layer 3: component overrides — plain CSS variables.
    if (components.length > 0) {
      emitBlock(
        lb,
        ":root",
        graph,
        components,
        "base",
        true,
        "/* Component tokens (aliased to semantic/primitive where possible) */",
      );
    }

    return lb.build();
  },
};
