// CSS renderer — produces tokens.css from a TokenGraph.
// Three cascade sections matching build-tokens.mjs:
//   1. :root primitives (no aliases resolved — literal values)
//   2. :root + html.light + [data-theme="light"] semantic light
//      html.dark + [data-theme="dark"] semantic dark
//   3. :root component overrides (aliased where possible)

import type {
  GraphLayer,
  TextRenderer,
  Theme,
  TokenGraph,
  TokenNode,
} from "../token-graph.js";
import { LineBuilder } from "./line-builder.js";

const HEADER = [
  "/* Generated by buildGraph + cssRenderer — do not edit by hand */",
  "/* Source: components/*.tokens.json (Figma W3C export) */",
];

function nodesByLayer(
  graph: TokenGraph,
  layer: GraphLayer,
): TokenNode[] {
  const out: TokenNode[] = [];
  for (const node of graph.nodes.values()) {
    if (node.layer === layer) out.push(node);
  }
  return out;
}

/**
 * Format a single declaration. If a resolved alias for the requested
 * variant exists, emit `var(--target)`, else emit the literal cssValue.
 * Returns `null` if there is no value for this variant on this node.
 */
function declFor(
  node: TokenNode,
  variant: "base" | Theme,
  useAlias: boolean,
): string | null {
  const aliasVariant = useAlias ? node.alias[variant] : undefined;
  const value =
    aliasVariant !== undefined
      ? `var(--${aliasVariant.to})`
      : node.cssValue[variant];
  if (value === undefined) return null;
  return `  --${node.id}: ${value};`;
}

function emitBlock(
  lb: LineBuilder,
  selector: string,
  nodes: readonly TokenNode[],
  variant: "base" | Theme,
  useAlias: boolean,
  sectionLabel?: string,
): void {
  if (sectionLabel) lb.push(sectionLabel);
  lb.push(`${selector} {`);
  for (const node of nodes) {
    const decl = declFor(node, variant, useAlias);
    if (decl !== null) lb.pushWithToken(decl, node.id);
  }
  lb.push("}");
  lb.blank();
}

export const cssRenderer: TextRenderer = {
  id: "tokens.css",
  render(graph: TokenGraph) {
    const lb = new LineBuilder();
    for (const h of HEADER) lb.push(h);
    lb.blank();

    const primitives = nodesByLayer(graph, "primitive");
    const semantics = nodesByLayer(graph, "semantic");
    const components = nodesByLayer(graph, "component");

    // Layer 1: primitives — literal values, no alias resolution.
    if (primitives.length > 0) {
      emitBlock(lb, ":root", primitives, "base", false);
    }

    // Layer 2a: semantic light — alias-resolved.
    const lightNodes = semantics.filter((n) => n.cssValue.light !== undefined);
    if (lightNodes.length > 0) {
      emitBlock(
        lb,
        ':root, html.light, [data-theme="light"]',
        lightNodes,
        "light",
        true,
        "/* Semantic — light theme (default) */",
      );
    }

    // Layer 2b: semantic dark — alias-resolved.
    const darkNodes = semantics.filter((n) => n.cssValue.dark !== undefined);
    if (darkNodes.length > 0) {
      emitBlock(
        lb,
        'html.dark, [data-theme="dark"]',
        darkNodes,
        "dark",
        true,
        "/* Semantic — dark theme */",
      );
    }

    // Layer 3: component overrides — alias-resolved where possible.
    if (components.length > 0) {
      emitBlock(
        lb,
        ":root",
        components,
        "base",
        true,
        "/* Component tokens (aliased to semantic/primitive where possible) */",
      );
    }

    return lb.build();
  },
};
