// Renders custom-components.ts — recipe objects for two categories of Nuxt UI
// incompatibility: components flagged `component-looks-custom` (foreign parts
// Nuxt has no slot for) and overlay-surface overrides (component appearance on
// a dark/light overlay — no Nuxt prop exists). Apply recipes via tv().

import type { TextRenderer, TokenGraph, RenderedText } from "../token-graph.js";
import type { ComponentRecipe } from "../recipe-engine.js";
import type { SlotMappingOverride } from "@tg/grammar";
import { buildCustomRecipes, buildOverlayRecipes } from "../custom-recipe-engine.js";
import { LineBuilder } from "./line-builder.js";

export interface CustomComponentsRendererOptions {
  /** component → foreign parts, from customPartsByComponent(scanReport). */
  customParts?: ReadonlyMap<string, ReadonlyArray<string>>;
  defaultSizeByComponent?: Readonly<Record<string, string>>;
  /** Session resolve overrides, so the rendered output matches the Kit preview. */
  slotMappingOverride?: SlotMappingOverride;
}

interface CustomComponentsRenderer extends TextRenderer {
  render(graph: TokenGraph, options?: CustomComponentsRendererOptions): RenderedText;
}

export const customComponentsRenderer: CustomComponentsRenderer = {
  id: "custom-components.ts",
  render(graph: TokenGraph, options?: CustomComponentsRendererOptions): RenderedText {
    const parts = options?.customParts ?? new Map();
    const recipes = {
      ...buildCustomRecipes(graph, parts, {
        defaultSizeByComponent: options?.defaultSizeByComponent,
        slotMappingOverride: options?.slotMappingOverride,
      }),
      ...buildOverlayRecipes(graph),
    };
    const names = Object.keys(recipes).sort();
    if (names.length === 0) {
      return new LineBuilder().build();
    }

    const lb = new LineBuilder();
    lb.push("// Generated by build-cli — recipes Nuxt UI cannot express natively:");
    lb.push("// custom components (foreign parts Nuxt has no slot for) AND overlay-surface");
    lb.push("// overrides (component appearance on a dark/light overlay — no Nuxt prop exists).");
    lb.push("// Hand-apply via tailwind-variants: const ui = tv(chipRecipe) / tv(base, buttonOverlayDarkRecipe).");
    lb.blank();
    for (const name of names) {
      emitCustomRecipe(lb, name, recipes[name]!);
      lb.blank();
    }
    return lb.build();
  },
};

function emitCustomRecipe(lb: LineBuilder, name: string, recipe: ComponentRecipe): void {
  lb.push(`export const ${name}Recipe = {`);

  const slotEntries = Object.entries(recipe.slots);
  if (slotEntries.length > 0) {
    lb.push("  slots: {");
    for (const [slot, classes] of slotEntries.sort(([a], [b]) => a.localeCompare(b))) {
      lb.push(`    ${slot}: ${JSON.stringify(classes)},`);
    }
    lb.push("  },");
  }

  const axes = ["size", "color", "variant"] as const;
  const variantsPresent = axes.some(
    (a) => Object.keys(recipe.variants[a] ?? {}).length > 0,
  );
  if (variantsPresent) {
    lb.push("  variants: {");
    for (const axis of axes) {
      const axisMap = recipe.variants[axis];
      if (!axisMap || Object.keys(axisMap).length === 0) continue;
      lb.push(`    ${axis}: {`);
      for (const variantKey of Object.keys(axisMap).sort()) {
        const slotMap = axisMap[variantKey];
        if (slotMap === undefined) continue;
        lb.push(`      ${variantKey}: {`);
        for (const [slot, classes] of Object.entries(slotMap).sort(([a], [b]) => a.localeCompare(b))) {
          lb.push(`        ${slot}: ${JSON.stringify(classes)},`);
        }
        lb.push("      },");
      }
      lb.push("    },");
    }
    lb.push("  },");
  }

  lb.push("} as const;");
}
