// Tailwind-utility-first CSS renderer.
//
// Consumes the classification map for a TokenGraph and emits:
//   @theme { ... }       (Tailwind v4 theme block)
//   .dark { ... }        (mode-variant overrides)
//
// Tokens classified as `tailwind-default` or `skip` produce no output.

import type { TextRenderer, TokenGraph } from "../token-graph.js";
import { LineBuilder } from "./line-builder.js";
import { classifyGraph, type Classification } from "../classify-token.js";
import { collectTypographyComposites } from "./typography-composites.js";

type SectionKey =
  | "primitive-colors"
  | "mode-invariant-brand"
  | "non-default-spacing"
  | "non-default-radius"
  | "non-default-font"
  | "mode-variant-semantics"
  | "mode-variant-shadows";

const SECTION_HEADERS: ReadonlyArray<readonly [SectionKey, string]> = [
  ["primitive-colors", "Primitive Colors"],
  ["mode-invariant-brand", "Mode-invariant Brand Colors"],
  ["non-default-spacing", "Non-default Spacing"],
  ["non-default-radius", "Non-default Radius"],
  ["non-default-font", "Non-default Typography"],
  ["mode-variant-semantics", "Mode-variant Semantics (light defaults)"],
  ["mode-variant-shadows", "Mode-variant Shadows"],
];

interface ThemeEntry {
  cssName: string;
  value: string;
  tokenId: string;
  modeInvariantHint: boolean;
}

interface DarkOverride {
  cssName: string;
  value: string;
  tokenId: string;
}

export const tokensCssRenderer: TextRenderer = {
  id: "tokens.css",
  render(graph: TokenGraph) {
    const classifications = classifyGraph(graph);
    const sections = new Map<SectionKey, ThemeEntry[]>();
    for (const [key] of SECTION_HEADERS) {
      sections.set(key, []);
    }

    const darkOverrides: DarkOverride[] = [];

    for (const [tokenId, classification] of classifications) {
      const node = graph.nodes.get(tokenId);
      if (!node) continue;
      bucketize(node.id, node.type, classification, sections, darkOverrides);
    }

    // Typography roles (typography-<role>-*) live in the component layer and are
    // skipped by classifyToken; re-surface the type-scale roles as Tailwind v4
    // composite --text-<role> custom properties.
    for (const entry of collectTypographyComposites(graph)) {
      push(sections, "non-default-font", {
        cssName: entry.cssName,
        value: entry.value,
        tokenId: entry.tokenId,
        modeInvariantHint: false,
      });
    }

    const lb = new LineBuilder();
    lb.push("/* Generated by build-cli — do not edit by hand */");
    lb.push("/* Source: components/*.tokens.json */");
    lb.blank();
    lb.push("@theme {");
    let firstSection = true;
    for (const [sectionKey, label] of SECTION_HEADERS) {
      const entries = sections.get(sectionKey) ?? [];
      if (entries.length === 0) continue;
      if (!firstSection) lb.blank();
      firstSection = false;
      lb.push(`  /* — ${label} — */`);
      entries.sort((a, b) => a.cssName.localeCompare(b.cssName));
      for (const entry of entries) {
        if (entry.modeInvariantHint) {
          lb.push("  /* mode-invariant: same in light + dark */");
        }
        lb.pushWithToken(`  ${entry.cssName}: ${entry.value};`, entry.tokenId);
      }
    }
    lb.push("}");

    if (darkOverrides.length > 0) {
      lb.blank();
      lb.push("/* Dark mode overrides */");
      lb.push(".dark {");
      darkOverrides.sort((a, b) => a.cssName.localeCompare(b.cssName));
      for (const o of darkOverrides) {
        lb.pushWithToken(`  ${o.cssName}: ${o.value};`, o.tokenId);
      }
      lb.push("}");
    }

    lb.blank();
    return lb.build();
  },
};

function bucketize(
  tokenId: string,
  tokenType: string,
  c: Classification,
  sections: Map<SectionKey, ThemeEntry[]>,
  darkOverrides: DarkOverride[],
): void {
  if (c.kind === "skip" || c.kind === "tailwind-default") return;

  if (c.kind === "theme-mode-variant") {
    const isShadow = tokenType === "shadow";
    const key: SectionKey = isShadow
      ? "mode-variant-shadows"
      : "mode-variant-semantics";
    push(sections, key, {
      cssName: c.cssName,
      value: c.lightValue,
      tokenId,
      modeInvariantHint: false,
    });
    darkOverrides.push({
      cssName: c.cssName,
      value: c.darkValue,
      tokenId,
    });
    return;
  }

  // theme-static
  const key = sectionFor(tokenType, c.cssName, c.modeInvariantHint);
  push(sections, key, {
    cssName: c.cssName,
    value: c.value,
    tokenId,
    modeInvariantHint: c.modeInvariantHint,
  });
}

function push(
  sections: Map<SectionKey, ThemeEntry[]>,
  key: SectionKey,
  entry: ThemeEntry,
): void {
  const arr = sections.get(key) ?? [];
  arr.push(entry);
  sections.set(key, arr);
}

function sectionFor(
  tokenType: string,
  cssName: string,
  modeInvariantHint: boolean,
): SectionKey {
  if (tokenType === "color") {
    return modeInvariantHint ? "mode-invariant-brand" : "primitive-colors";
  }
  if (cssName.startsWith("--spacing-")) return "non-default-spacing";
  if (cssName.startsWith("--radius-") || cssName.startsWith("--rounded-")) {
    return "non-default-radius";
  }
  if (
    cssName.startsWith("--text-") ||
    cssName.startsWith("--font-") ||
    cssName.startsWith("--leading-") ||
    cssName.startsWith("--tracking-") ||
    cssName.startsWith("--letter-spacing-") ||
    cssName.startsWith("--line-height-")
  ) {
    return "non-default-font";
  }
  // Fallback for unrecognized prefixes.
  return "primitive-colors";
}
