// TypeScript renderer — produces tokens.ts from a TokenGraph.
// Emits one entry per token id with its base/light value as the canonical
// string. The dark variant is exposed under a parallel object so the
// inspector can show both without the consumer needing to switch themes.

import type { TextRenderer, TokenGraph } from "../token-graph.js";
import { LineBuilder } from "./line-builder.js";

function pickValue(node: { cssValue: { base?: string; light?: string; dark?: string } }):
  | string
  | undefined {
  return node.cssValue.base ?? node.cssValue.light ?? node.cssValue.dark;
}

export const tsRenderer: TextRenderer = {
  id: "tokens.ts",
  render(graph: TokenGraph) {
    const lb = new LineBuilder();
    lb.push("// Generated by buildGraph + tsRenderer — do not edit by hand");
    lb.blank();
    lb.push("export const tokens = {");
    const sorted = [...graph.nodes.values()].sort((a, b) =>
      a.id.localeCompare(b.id),
    );
    for (const node of sorted) {
      const value = pickValue(node);
      if (value === undefined) continue;
      lb.pushWithToken(
        `  ${JSON.stringify(node.id)}: ${JSON.stringify(value)},`,
        node.id,
      );
    }
    lb.push("} as const;");
    lb.blank();
    lb.push("export type TokenName = keyof typeof tokens;");
    lb.blank();
    lb.push(
      "export const cssVar = (name: TokenName): string => `var(--${name})`;",
    );
    lb.blank();
    return lb.build();
  },
};
