// A short, stakeholder-readable "start here" guide for the export. Cross-cutting
// (not a target): the instructional counterpart to REPORT.md's diagnostic. Static
// + deterministic — it describes what each target's files are and where they go.

export function buildUsageGuide(): string {
  return `# Using this export

Generated by token-inspector from your Figma design tokens. Each folder targets a
different system — use the one(s) you need.

## Nuxt UI — \`nuxt/\`, \`css/\`, \`kit/\`

- \`nuxt/app.config.ts\` — copy into your Nuxt app's \`app.config.ts\` (the \`ui\` recipes).
- \`nuxt/custom-components.ts\` — hand-built recipes for components Nuxt UI can't theme
  generically (only present when needed); merge into your app config.
- \`css/tokens.css\` — the Tailwind v4 \`@theme\` design tokens; \`@import\` it in your app CSS.
- \`kit/\` — a runnable preview of the themed components: \`cd kit && npm install && npm run dev\`.

## shadcn/ui — \`shadcn/globals.css\`

Paste the \`:root\`, \`.dark\`, and \`@theme inline\` blocks into your shadcn/ui app's
\`globals.css\`, replacing the defaults. Colors are OKLCH, matching shadcn's convention.

## Framework-agnostic tokens — \`tokens/\`

For any non-Tailwind consumer (plain CSS, React, Svelte, Style Dictionary, mobile):

- \`tokens/variables.css\` — plain \`:root\` + \`.dark\` CSS custom properties; \`@import\` anywhere.
- \`tokens/tokens.json\` — a flat \`{ value, dark? }\` map; feed Style Dictionary or any tooling.
- \`tokens/tokens.ts\` — \`import { tokens } from "./tokens"\` for typed, autocompleted access.

---

See \`REPORT.md\` for a health digest of the design system — coverage, deviations by
owner, and per-target diagnostics.
`;
}
