import type { TokenGraph } from "../../token-graph.js";

// Framework-agnostic export of the design-token layer. Unlike css/tokens.css
// (Tailwind v4 `@theme`, useless without Tailwind) and shadcn/globals.css (shadcn's
// var names), this emits the resolved tokens under their OWN names as plain CSS
// custom properties + a flat JSON — usable by any framework (plain CSS, React,
// Svelte, Style Dictionary pipelines, mobile, …).
//
// Scope: every non-component token (the 145 primitive + 51 semantic design tokens).
// Component-layer tokens are excluded — they become recipe classes, not vars.

interface GenericToken {
  readonly id: string;
  readonly value: string;
  readonly dark?: string;
}

function collect(graph: TokenGraph): GenericToken[] {
  const out: GenericToken[] = [];
  for (const node of graph.nodes.values()) {
    if (node.layer === "component") continue;
    const value = node.cssValue?.base ?? node.cssValue?.light;
    if (value === undefined) continue;
    const dark = node.cssValue?.dark;
    out.push(dark !== undefined && dark !== value ? { id: node.id, value, dark } : { id: node.id, value });
  }
  return out.sort((a, b) => a.id.localeCompare(b.id));
}

export function buildGenericTs(graph: TokenGraph): string {
  const lines: string[] = [
    "// Framework-agnostic design tokens — generated by token-inspector.",
    "",
    "export const tokens = {",
  ];
  for (const t of collect(graph)) {
    const entry =
      t.dark !== undefined
        ? `{ value: ${JSON.stringify(t.value)}, dark: ${JSON.stringify(t.dark)} }`
        : `{ value: ${JSON.stringify(t.value)} }`;
    lines.push(`  ${JSON.stringify(t.id)}: ${entry},`);
  }
  lines.push("} as const;", "", "export type TokenName = keyof typeof tokens;");
  return lines.join("\n") + "\n";
}

/** Coverage of the generic export: how many design tokens were emitted and how
 *  many carry a dark-mode override. */
export function genericTokenStats(graph: TokenGraph): { total: number; dark: number } {
  const tokens = collect(graph);
  return { total: tokens.length, dark: tokens.filter((t) => t.dark !== undefined).length };
}

export function buildGenericCss(graph: TokenGraph): string {
  const tokens = collect(graph);
  const lines: string[] = [
    "/* Framework-agnostic design tokens — generated by token-inspector. */",
    "",
    ":root {",
  ];
  for (const t of tokens) lines.push(`  --${t.id}: ${t.value};`);
  lines.push("}", "", ".dark {");
  for (const t of tokens) if (t.dark !== undefined) lines.push(`  --${t.id}: ${t.dark};`);
  lines.push("}");
  return lines.join("\n") + "\n";
}

export function buildGenericJson(graph: TokenGraph): string {
  const obj: Record<string, { value: string; dark?: string }> = {};
  for (const t of collect(graph)) {
    obj[t.id] = t.dark !== undefined ? { value: t.value, dark: t.dark } : { value: t.value };
  }
  return JSON.stringify(obj, null, 2) + "\n";
}
