// Generates packages/grammar/src/nuxt-slots.generated.ts from Nuxt UI's theme
// definitions. Reads the installed @nuxt/ui version, fetches that tag's theme
// source files from GitHub for INCLUDE_LIST, extracts slot keys via the AST, and
// writes a committed, deterministic file. Run: npm run gen:vocab
import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { execFileSync } from "node:child_process";
import { extractSlotKeys } from "../packages/grammar/src/extract-theme-slots.ts";
import { INCLUDE_LIST, FIGMA_THEME_FILE } from "../packages/grammar/src/nuxt-vocab-curated.ts";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const version = JSON.parse(
  readFileSync(resolve(root, "node_modules/@nuxt/ui/package.json"), "utf8"),
).version;
const tag = `v${version}`;
console.log(`generating vocab from @nuxt/ui ${tag}`);

function themeSource(figmaName: string): string {
  const file = FIGMA_THEME_FILE.get(figmaName) ?? figmaName;
  const out = execFileSync(
    "gh",
    ["api", `repos/nuxt/ui/contents/src/theme/${file}.ts?ref=${tag}`, "--jq", ".content"],
    { encoding: "utf8" },
  );
  return Buffer.from(out.trim(), "base64").toString("utf8");
}

const entries: Array<[string, string[]]> = [];
for (const name of INCLUDE_LIST) {
  const slots = extractSlotKeys(themeSource(name));
  entries.push([name, slots]);
  console.log(`  ${name}: ${slots.length} slot(s)`);
}

const body = entries
  .map(([n, slots]) => `  [${JSON.stringify(n)}, new Set(${JSON.stringify(slots)})],`)
  .join("\n");
const file = `// GENERATED by scripts/gen-nuxt-vocab.ts from @nuxt/ui ${tag} — do not edit by hand.
// Re-run: npm run gen:vocab
export const GENERATED_NUXT_SLOTS: ReadonlyMap<string, ReadonlySet<string>> = new Map([
${body}
]);

export const GENERATED_COMPONENTS: readonly string[] = ${JSON.stringify(entries.map(([n]) => n))};
`;
writeFileSync(resolve(root, "packages/grammar/src/nuxt-slots.generated.ts"), file);
console.log(`wrote packages/grammar/src/nuxt-slots.generated.ts (${entries.length} components)`);
