import sdk from "@stackblitz/sdk";
import type { LiveBuildSubstrate } from "./substrate.js";

const DESCRIPTION = "Live build of your token export (generated by Token Inspector).";

export const stackblitzSubstrate: LiveBuildSubstrate = {
  openExternal(files, opts) {
    sdk.openProject(
      { title: opts.title, description: DESCRIPTION, template: "node", files },
      { newWindow: true },
    );
  },
};
