import sdk from "@stackblitz/sdk";
import type { LiveBuildSubstrate } from "./substrate.js";

const DESCRIPTION = "Live build of your token export (generated by Token Inspector).";

export const stackblitzSubstrate: LiveBuildSubstrate = {
  async embed(el, files, opts) {
    await sdk.embedProject(
      el,
      { title: opts.title, description: DESCRIPTION, template: "node", files },
      { view: "preview", hideExplorer: true, hideNavigation: true, height: "100%", openFile: "src/App.vue" },
    );
  },
  openExternal(files, opts) {
    sdk.openProject(
      { title: opts.title, description: DESCRIPTION, template: "node", files },
      { newWindow: true },
    );
  },
};
